version: "3.3"
services:
    app:
        build: .
        image: nginx:latest
        ports:
            - "2711:3000"
        volumes:
            - .:/app
        environment:
            - NODE_ENV=production
