version: "3.3" # Hoặc 2.2, thay vì 3.8
services:
    app:
        build: .
        ports:
            - "2711:3000"
        volumes:
            - ./src/app:/app
        environment:
            - NODE_ENV=production
